import { createElement } from "lwc";
import Swan_AmazonFileUploaderModalFile from "c/swan_AmazonFileUploaderModalFile";

describe("c-swan-amazon-file-uploader-modal-file", () => {
	afterEach(() => {
		// The jsdom instance is shared across test cases in a single file so reset the DOM
		while (document.body.firstChild) {
			document.body.removeChild(document.body.firstChild);
		}
	});

	it("TODO: test case generated by CLI command, please fill in test logic", () => {
		// Arrange
		const element = createElement(
			"c-swan-amazon-file-uploader-modal-file",
			{
				is: Swan_AmazonFileUploaderModalFile
			}
		);

		// Act
		document.body.appendChild(element);

		// Assert
		// const div = element.shadowRoot.querySelector('div');
		expect(1).toBe(1);
	});
});
